name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "9f95a771-ceb1-48f4-8bba-872d50568906"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "9f95a771-ceb1-48f4-8bba-872d50568906"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
